apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
    - image: harbor.cyverse.org/de/discoenv-oxidize
      context: .
      docker:
        cacheFrom:
          - harbor.cyverse.org/de/discoenv-oxidize
  local: {}
manifests:
    rawYaml:
      - k8s/user-info.yaml