apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoenv
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: discoenv
  template:
    metadata:
      labels:
        de-app: discoenv
        app: de
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - discoenv
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
             - key: jobservices.yml
               path: service.yml
      containers:
      - name: discoenv
        image: harbor.cyverse.org/de/discoenv-oxidize
        command: ["/user-info"]
        env:
          - name: SERVICE_NAME
            value: discoenv
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        ports:
          - name: listen-port
            containerPort: 60000
        resources:
          requests:
            cpu: "1m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/cyverse/de/configs
            readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: discoenv
spec:
  selector:
    de-app: discoenv
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
