apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-info
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: user-info
  template:
    metadata:
      labels:
        de-app: user-info
        app: de
    spec:
      serviceAccountName: user-info
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - user-info
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
      containers:
      - name: user-info
        image: harbor.cyverse.org/de/user-info
        resources:
          requests:
            cpu: "1m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        args:
          - --user-domain
          - "@$(USER_SUFFIX)"
          - --database-url
          - "${DE_DATABASE_URI}"
        env:
          - name: SERVICE_NAME
            value: user-info
          - name: USER_SUFFIX
            valueFrom:
              secretKeyRef:
                name: configs
                key: USER_SUFFIX
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          - name: DE_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: configs
                key: DE_DATABASE_URI
        ports:
          - name: listen-port
            containerPort: 60000
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
        livenessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-info
spec:
  selector:
    de-app: user-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port